blank_issues_enabled: false
contact_links:
  - name: Contributing to [YOUR PROJECT]
    url: https://github.com/[YOUR NAME]/[YOUR PROJECT]/blob/main/CONTRIBUTING.md
    about: Guidelines for how to report an issue.
  - name: Support
    url: https://github.com/[YOUR NAME]/[YOUR PROJECT]/discussions
    about: Ask the community for support
  - name: Documentation
    url: https://github.com/[YOUR NAME]/[YOUR PROJECT]/wiki
    about: Many questions might be already answered here.
